### PR TITLE
epee: basic sanity check on allocation size from untrusted source

### PR DESCRIPTION
**Pull request by pallas1**
https://github.com/monero-project/monero/commit/39169ace09f702b8ae66fe373424e5c0b1326a6d

### CODE REVIEW

**Comment by pallas1** [comment]
This is probably not even needed. See here:

https://hackerone.com/reports/506498

It looks like the issue is linked to the "reserve" method, which we do not even have.
It shouldn't hurt, either.

**Comment by valiant1x** [comment]
@pallas1 looks simple enough - was this tested through a scratch resync?

**Comment by pallas1** [comment]
Not from scratch, just some days, will test from scratch now.

**Comment by pallas1** [comment]
sync from scratch succesfull

**Pull request merged**
