### PR TITLE
Next block difficulty cache

### PR DESCRIPTION
**Pull request by pallas1**
Should be a good speedup for pools and other services.

### CODE REVIEW

**Comment by pallas1** [comment]
this is the only PR left which is still not using the new git protocol, should we ask pool operator(s) to test it?

**Comment by iedemam** [comment]
How do we feel about this for b3?

**Comment by pallas1** [comment]
conflicts resolved

**Comment by pallas1** [comment]
we will probably need to merge this as well:
https://github.com/monero-project/monero/pull/4806

**Comment by pallas1** [comment]
And this: https://github.com/monero-project/monero/pull/5373

**Comment by valiant1x** [comment]
Deferred until full 0.14 rebase

**Pull request closed without merging**
